server:
#  port: 8080
  port: 9091

spring:
  application:
    name: mall-tiny-oa
  profiles:
    active: dev
#  main:
#    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: mall
  key:
    admin: 'ums-oa:admin'
    resourceList: 'ums-oa:resourceList'
  expire:
    common: 86400 # 24小时

devtools:
  livereload:
    enabled: true
    port: 9527
  restart:
    enabled: true

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /ams/amsActivity/*
aliyun:
  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tJn7LvqiJKsCyy2u7vr # 访问身份验证中用到用户标识
    accessKeySecret: VrIrc4lo1PpRDnyZV7gmaDWnm5yamX # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: guoda365 # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://39.104.170.41:9091/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: oaimg/ # 上传文件夹路径前缀